name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.1
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
      - run: pnpm install
      - name: build
        # run: pnpm release:build
        run: |
          lerna run \
          --parallel \
          --no-private \
          --scope "@mui/x-data-grid-premium" \
          --scope "@mui/x-data-grid-pro" \
          --scope "@mui/x-data-grid" \
          --scope "@mui/x-internals" \
          build
      - name: publish
        # run: pnpm release:publish
        run: |
          echo '@mui:registry=https://npm.pkg.github.com/boonya' >> .npmrc
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.GHCR_TOKEN_RW }}' >> .npmrc
          pnpm publish \
          --recursive \
          --tag canary \
          --no-git-checks \
          --publish-branch 7.23.0+issue-13261
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHCR_TOKEN_RW }}
