name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.1
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
      - run: pnpm install
      - run: pnpm release:build
      - run: release:publish
    #   - run: npm publish --tag canary # ${{ github.event.release.prerelease && 'prerelease' || 'latest' }}
    #     env:
    #       NODE_AUTH_TOKEN: ${{ secrets.GHCR_TOKEN_RW }}
